version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: foo
  postgres:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: foo
